### ISSUE TITLE
Scheduled Tasks Fail

### ISSUE THREAD

**Issue by automate-this** [rconfig/rconfig6-docker#3]
Scheduled tasks do not run.
Starting a task (Config Backup, System Backup, Compliance Check) manually, returns
"Server Error".
I have found no logs regarding this and also nothing in horizon jobs.

**Comment by automate-this** [comment]
Rebuilt Containers and updated rConfig. Problem still persists.

**Comment by automate-this** [comment]
Browser Console Errors:
POST http://rconfigserver:8080/api/tasks/run-manual-task 500 (Internal Server Error)

{
    "500": {
        "message": "Request failed with status code 500",
        "name": "AxiosError",
        "config": {
            "transitional": {
                "silentJSONParsing": true,
                "forcedJSONParsing": true,
                "clarifyTimeoutError": false
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1,
            "env": {
                "FormData": null
            },
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "X-Requested-With": "XMLHttpRequest",
                "Content-Type": "application/json",
                "X-XSRF-TOKEN": "secret"
            },
            "method": "post",
            "url": "/api/tasks/run-manual-task",
            "data": "{\"id\":659367}"
        },
        "code": "ERR_BAD_RESPONSE",
        "status": 500
    }
}

**Comment by stephenstack** [comment]
Can you login login into both the apache and horizon containers and run the following from within the 'current' dir
Php artisan rconfig:clear-all

**Comment by automate-this** [comment]
Done. Still not working.
Command Output (same on both containers):
 ------  Begin rConfig Laravel Clear Out!  ------
------  Config Cleared!  ------
------  Cache Cleared!  ------
------  Routes Cleared!  ------
------  Views Cleared!  ------
------  Config Cached!  ------
------  Routes Cached!  ------
------  Views Cached!  ------
------  Optimized!  ------
------  Queues Restarted!  ------
sh: 1: sudo: not found

sh: 1: sudo: not found

sh: 1: sudo: not found

sh: 1: composer: not found

^ "chown(): Unable to find uid for apache"
rConfig6 - Network Configuration Management application settings have been cleared!

**Comment by stephenstack** [comment]
What specifically are you doing that causes the 500 error?

**Comment by automate-this** [comment]
Going to "Scheduled Tasks" and clicking start on any task that i have created.
System Backup
Config Backup
Compliance Check

**Comment by automate-this** [comment]
/var/cron.log on cron container shows:
```
In Connection.php line 759:

  could not find driver (SQL: select * from information_schema.tables where t
  able_schema = rconfig343 and table_name = settings and table_type = 'BASE T
  ABLE')


In Connector.php line 70:

  could not find driver

```

**Comment by rconfig** [comment]
This is an application issue, we will contact you re the fix today

**Comment by automate-this** [comment]
On a side note: It seems there is no php mysql driver installed on the cron container, which results in the cron.log I have posted before.
You can add php extensions to the official php docker images using
`docker-php-ext-install pdo pdo_mysql`
in your Dockerfile.

See https://hub.docker.com/_/php
