### ISSUE TITLE
"Install" fails because `config6-docker-envoy.blade.php` not downloadable

### ISSUE THREAD

**Issue by rkube-rvk** [rconfig/rconfig6-docker#6]
In `php-apache` container, I get to following error:

```
root@209de293be94:/var/www/html/rconfig6# wget https://www.rconfig.com/downloads/rconfig6-docker-envoy.blade.php -O /var/www/html/rconfig6/Envoy.blade.php
--2024-08-29 14:19:29--  https://www.rconfig.com/downloads/rconfig6-docker-envoy.blade.php
Resolving www.rconfig.com (www.rconfig.com)... 74.234.33.54
Connecting to www.rconfig.com (www.rconfig.com)|74.234.33.54|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-29 14:19:29 ERROR 404: Not Found.

```

**Comment by matfremz** [comment]
Hello, i have the same error, any news regarding a resolution ?

**Comment by nedzad-winter** [comment]
Hello!

Same on my side.
Did any of you found a workaround ?

**Comment by stephenstack** [comment]
Hi,
There is some confustion around the install instructions, can you let me know where you find the steps to download this paticular file? Is it from https://v6docs.rconfig.com/getstarted/os-setup.
Please use the scripts from https://docs.rconfig.com/getstarted/os-setup

**Comment by stephenstack** [comment]
I just reread the oroginal complaint, this download will work now. please try again

**Comment by rkube-rvk** [comment]
> I just reread the oroginal complaint, this download will work now. please try again

Thanks!
